services:

  postgres:
    image: postgres:16
    container_name: gamertrials-db
    restart: always
    environment:
      POSTGRES_DB: gamertrials
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - gamertrials_postgres_data:/var/lib/postgresql/data
    networks:
      - gamertrials-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: gamertrials-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gamertrials.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - gamertrials_pgadmin_data:/var/lib/pgadmin
    networks:
      - gamertrials-net

  app:
    build: .
    container_name: gamertrials-app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gamertrials
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - gamertrials-net

volumes:
  gamertrials_postgres_data:
    external: true
  gamertrials_pgadmin_data:
    external: true

networks:
  gamertrials-net:
    driver: bridge