package com.malpishon.gamertrials.model;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public enum GameList {
    COUNTER_STRIKE_2("Counter-Strike 2"),
    COUNTER_STRIKE_GO("Counter-Strike: Global Offensive"),
    LEAGUE_OF_LEGENDS("League of Legends"),
    DOTA_2("Dota 2"),
    VALORANT("Valorant"),
    FORTNITE("Fortnite"),
    APEX_LEGENDS("Apex Legends"),
    CALL_OF_DUTY_WARZONE("Call of Duty: Warzone"),
    CALL_OF_DUTY_MW3("Call of Duty: Modern Warfare III"),
    CALL_OF_DUTY_BO6("Call of Duty: Black Ops 6"),
    OVERWATCH_2("Overwatch 2"),
    RAINBOW_SIX_SIEGE("Rainbow Six Siege"),
    ROCKET_LEAGUE("Rocket League"),
    PUBG("PUBG: Battlegrounds"),
    MINECRAFT("Minecraft"),
    GTA_V("Grand Theft Auto V"),
    GTA_ONLINE("Grand Theft Auto Online"),
    GTA_VI("Grand Theft Auto VI"),
    RED_DEAD_REDEMPTION_2("Red Dead Redemption 2"),
    WORLD_OF_WARCRAFT("World of Warcraft"),
    FINAL_FANTASY_XIV("Final Fantasy XIV"),
    DESTINY_2("Destiny 2"),
    ESCAPE_FROM_TARKOV("Escape from Tarkov"),
    RUST("Rust"),
    DEAD_BY_DAYLIGHT("Dead by Daylight"),
    EA_SPORTS_FC_25("EA Sports FC 25"),
    NBA_2K25("NBA 2K25"),
    MADDEN_NFL_25("Madden NFL 25"),
    STREET_FIGHTER_6("Street Fighter 6"),
    MORTAL_KOMBAT_1("Mortal Kombat 1"),
    TEKKEN_8("Tekken 8"),
    STARCRAFT_2("StarCraft II"),
    AGE_OF_EMPIRES_4("Age of Empires IV"),
    CIVILIZATION_6("Civilization VI"),
    CIVILIZATION_7("Civilization VII"),
    AMONG_US("Among Us"),
    FALL_GUYS("Fall Guys"),
    ROBLOX("Roblox"),
    GENSHIN_IMPACT("Genshin Impact"),
    HONKAI_STAR_RAIL("Honkai: Star Rail"),
    WUTHERING_WAVES("Wuthering Waves"),
    ZENLESS_ZONE_ZERO("Zenless Zone Zero"),
    THE_LAST_OF_US("The Last of Us"),
    LAST_OF_US_PART_2("The Last of Us Part II"),
    GOD_OF_WAR("God of War (2018)"),
    GOD_OF_WAR_RAGNAROK("God of War Ragnarök"),
    GOD_OF_WAR_3("God of War III"),
    GOD_OF_WAR_ASCENSION("God of War: Ascension"),
    UNCHARTED_4("Uncharted 4: A Thief's End"),
    UNCHARTED_LOST_LEGACY("Uncharted: The Lost Legacy"),
    UNCHARTED_COLLECTION("Uncharted: The Nathan Drake Collection"),
    ELDEN_RING("Elden Ring"),
    ELDEN_RING_SHADOW_OF_THE_ERDTREE("Elden Ring: Shadow of the Erdtree"),
    DARK_SOULS_3("Dark Souls III"),
    DARK_SOULS_REMASTERED("Dark Souls Remastered"),
    DARK_SOULS_2("Dark Souls II"),
    DEMONS_SOULS("Demon's Souls"),
    BLOODBORNE("Bloodborne"),
    SEKIRO("Sekiro: Shadows Die Twice"),
    LIES_OF_P("Lies of P"),
    LORDS_OF_THE_FALLEN("Lords of the Fallen"),
    REMNANT_2("Remnant II"),
    NIOH_2("Nioh 2"),
    MORTAL_SHELL("Mortal Shell"),
    CODE_VEIN("Code Vein"),
    SALT_AND_SANCTUARY("Salt and Sanctuary"),
    HOLLOW_KNIGHT("Hollow Knight"),
    HOLLOW_KNIGHT_SILKSONG("Hollow Knight: Silksong"),
    DYING_LIGHT_2("Dying Light 2 Stay Human"),
    DYING_LIGHT("Dying Light"),
    DYING_LIGHT_THE_BEAST("Dying Light: The Beast"),
    GHOST_OF_TSUSHIMA("Ghost of Tsushima"),
    GHOST_OF_YOTEI("Ghost of Yōtei"),
    HOGWARTS_LEGACY("Hogwarts Legacy"),
    BALDURS_GATE_3("Baldur's Gate 3"),
    DIABLO_4("Diablo IV"),
    DIABLO_3("Diablo III"),
    DIABLO_2_RESURRECTED("Diablo II: Resurrected"),
    PATH_OF_EXILE("Path of Exile"),
    PATH_OF_EXILE_2("Path of Exile 2"),
    LOST_ARK("Lost Ark"),
    BLACK_DESERT_ONLINE("Black Desert Online"),
    GUILD_WARS_2("Guild Wars 2"),
    ELDER_SCROLLS_ONLINE("The Elder Scrolls Online"),
    WARFRAME("Warframe"),
    HALO_INFINITE("Halo Infinite"),
    SEA_OF_THIEVES("Sea of Thieves"),
    PALWORLD("Palworld"),
    LETHAL_COMPANY("Lethal Company"),
    HELLDIVERS_2("Helldivers 2"),
    SPACE_MARINE_2("Warhammer 40,000: Space Marine 2"),
    WITCHER_3("The Witcher 3: Wild Hunt"),
    CYBERPUNK_2077("Cyberpunk 2077"),
    ASSASSINS_CREED_SHADOWS("Assassin's Creed Shadows"),
    ASSASSINS_CREED_VALHALLA("Assassin's Creed Valhalla"),
    ASSASSINS_CREED_MIRAGE("Assassin's Creed Mirage"),
    FAR_CRY_6("Far Cry 6"),
    MONSTER_HUNTER_WORLD("Monster Hunter World"),
    MONSTER_HUNTER_RISE("Monster Hunter Rise"),
    MONSTER_HUNTER_WILDS("Monster Hunter Wilds"),
    RESIDENT_EVIL_4("Resident Evil 4 Remake"),
    RESIDENT_EVIL_VILLAGE("Resident Evil Village"),
    DEVIL_MAY_CRY_5("Devil May Cry 5"),
    METAL_GEAR_SOLID_5("Metal Gear Solid V"),
    METAL_GEAR_SOLID_DELTA("Metal Gear Solid Delta: Snake Eater"),
    DAYS_GONE("Days Gone"),
    HORIZON_ZERO_DAWN("Horizon Zero Dawn"),
    HORIZON_FORBIDDEN_WEST("Horizon Forbidden West"),
    RATCHET_AND_CLANK_RIFT_APART("Ratchet & Clank: Rift Apart"),
    SPIDER_MAN("Marvel's Spider-Man"),
    SPIDER_MAN_2("Marvel's Spider-Man 2"),
    SPIDER_MAN_MILES_MORALES("Marvel's Spider-Man: Miles Morales"),
    STRAY("Stray"),
    IT_TAKES_TWO("It Takes Two"),
    A_WAY_OUT("A Way Out"),
    BACK_4_BLOOD("Back 4 Blood"),
    LEFT_4_DEAD_2("Left 4 Dead 2"),
    PAYDAY_2("Payday 2"),
    PAYDAY_3("Payday 3"),
    DIVISION_2("Tom Clancy's The Division 2"),
    WATCH_DOGS_LEGION("Watch Dogs Legion"),
    METRO_EXODUS("Metro Exodus"),
    STALKER_2("S.T.A.L.K.E.R. 2: Heart of Chornobyl"),
    STARFIELD("Starfield"),
    NO_MANS_SKY("No Man's Sky"),
    ELITE_DANGEROUS("Elite Dangerous"),
    STAR_CITIZEN("Star Citizen"),
    EVE_ONLINE("EVE Online"),
    SATISFACTORY("Satisfactory"),
    FACTORIO("Factorio"),
    TERRARIA("Terraria"),
    STARDEW_VALLEY("Stardew Valley"),
    VALHEIM("Valheim"),
    SEVEN_DAYS_TO_DIE("7 Days to Die"),
    ARK_SURVIVAL_EVOLVED("ARK: Survival Evolved"),
    ARK_SURVIVAL_ASCENDED("ARK: Survival Ascended"),
    CONAN_EXILES("Conan Exiles"),
    THE_FOREST("The Forest"),
    SONS_OF_THE_FOREST("Sons of The Forest"),
    SUBNAUTICA("Subnautica"),
    SUBNAUTICA_BELOW_ZERO("Subnautica: Below Zero"),
    GREEN_HELL("Green Hell"),
    PROJECT_ZOMBOID("Project Zomboid"),
    DAYZ("DayZ"),
    HUNT_SHOWDOWN("Hunt: Showdown"),
    HUNT_SHOWDOWN_1896("Hunt: Showdown 1896"),
    TARKOV_ARENA("Tarkov Arena"),
    SQUAD("Squad"),
    HELL_LET_LOOSE("Hell Let Loose"),
    INSURGENCY_SANDSTORM("Insurgency: Sandstorm"),
    READY_OR_NOT("Ready or Not"),
    ARMA_3("ARMA 3"),
    ARMA_REFORGER("ARMA Reforger"),
    DCS_WORLD("DCS World"),
    WAR_THUNDER("War Thunder"),
    WORLD_OF_TANKS("World of Tanks"),
    WORLD_OF_WARSHIPS("World of Warships"),
    ENLISTED("Enlisted"),
    BATTLEFIELD_2042("Battlefield 2042"),
    BATTLEFIELD_6("Battlefield 6"),
    BATTLEFIELD_5("Battlefield V"),
    BATTLEFIELD_1("Battlefield 1"),
    TITANFALL_2("Titanfall 2"),
    SPLITGATE("Splitgate"),
    HALO_MCC("Halo: The Master Chief Collection"),
    GEARS_5("Gears 5"),
    FOR_HONOR("For Honor"),
    CHIVALRY_2("Chivalry 2"),
    MORDHAU("Mordhau"),
    MOUNT_AND_BLADE_2("Mount & Blade II: Bannerlord"),
    TOTAL_WAR_WARHAMMER_3("Total War: Warhammer III"),
    COMPANY_OF_HEROES_3("Company of Heroes 3"),
    WARHAMMER_40K_DARKTIDE("Warhammer 40,000: Darktide"),
    WARHAMMER_VERMINTIDE_2("Warhammer: Vermintide 2"),
    DEEP_ROCK_GALACTIC("Deep Rock Galactic"),
    RISK_OF_RAIN_2("Risk of Rain 2"),
    BORDERLANDS_3("Borderlands 3"),
    BORDERLANDS_4("Borderlands 4"),
    TINY_TINAS_WONDERLANDS("Tiny Tina's Wonderlands"),
    OUTRIDERS("Outriders"),
    THE_CYCLE_FRONTIER("The Cycle: Frontier"),
    MARAUDERS("Marauders"),
    BLACK_MYTH_WUKONG("Black Myth: Wukong"),
    STELLAR_BLADE("Stellar Blade"),
    RISE_OF_THE_RONIN("Rise of the Ronin"),
    DRAGONS_DOGMA_2("Dragon's Dogma 2"),
    FINAL_FANTASY_XVI("Final Fantasy XVI"),
    FINAL_FANTASY_VII_REBIRTH("Final Fantasy VII Rebirth"),
    PERSONA_3_RELOAD("Persona 3 Reload"),
    METAPHOR_REFANTAZIO("Metaphor: ReFantazio"),
    LIKE_A_DRAGON_INFINITE_WEALTH("Like a Dragon: Infinite Wealth"),
    GRANBLUE_FANTASY_RELINK("Granblue Fantasy: Relink"),
    MAFIA_THE_OLD_COUNTRY("Mafia: The Old Country"),
    DOOM_THE_DARK_AGES("DOOM: The Dark Ages"),
    INDIANA_JONES_GREAT_CIRCLE("Indiana Jones and the Great Circle"),
    AVOWED("Avowed"),
    KINGDOM_COME_DELIVERANCE_2("Kingdom Come: Deliverance II"),
    OTHER("Other");

    private final String displayName;

    GameList(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }

    public static List<String> getAllGameNames() {
        return Arrays.stream(values())
                .map(GameList::getDisplayName)
                .collect(Collectors.toList());
    }
}

